/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PalestranteIdRouteImport } from './routes/palestrante.$id'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppPrebalancoRouteImport } from './routes/app.prebalanco'
import { Route as AppPalestrantesRouteImport } from './routes/app.palestrantes'
import { Route as AppLogisticaRouteImport } from './routes/app.logistica'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppJuridicoRouteImport } from './routes/app.juridico'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppComissoesRouteImport } from './routes/app.comissoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PalestranteIdRoute = PalestranteIdRouteImport.update({
  id: '/palestrante/$id',
  path: '/palestrante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPrebalancoRoute = AppPrebalancoRouteImport.update({
  id: '/prebalanco',
  path: '/prebalanco',
  getParentRoute: () => AppRoute,
} as any)
const AppPalestrantesRoute = AppPalestrantesRouteImport.update({
  id: '/palestrantes',
  path: '/palestrantes',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticaRoute = AppLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppJuridicoRoute = AppJuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppComissoesRoute = AppComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/orcamento': typeof OrcamentoRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/juridico': typeof AppJuridicoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/palestrantes': typeof AppPalestrantesRoute
  '/app/prebalanco': typeof AppPrebalancoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/vendas': typeof AppVendasRoute
  '/palestrante/$id': typeof PalestranteIdRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/orcamento': typeof OrcamentoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/juridico': typeof AppJuridicoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/palestrantes': typeof AppPalestrantesRoute
  '/app/prebalanco': typeof AppPrebalancoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/vendas': typeof AppVendasRoute
  '/palestrante/$id': typeof PalestranteIdRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/orcamento': typeof OrcamentoRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/juridico': typeof AppJuridicoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/logistica': typeof AppLogisticaRoute
  '/app/palestrantes': typeof AppPalestrantesRoute
  '/app/prebalanco': typeof AppPrebalancoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/vendas': typeof AppVendasRoute
  '/palestrante/$id': typeof PalestranteIdRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/catalogo'
    | '/orcamento'
    | '/portal'
    | '/app/admin'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/crm'
    | '/app/eventos'
    | '/app/financeiro'
    | '/app/juridico'
    | '/app/kanban'
    | '/app/logistica'
    | '/app/palestrantes'
    | '/app/prebalanco'
    | '/app/propostas'
    | '/app/vendas'
    | '/palestrante/$id'
    | '/app/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/orcamento'
    | '/app/admin'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/crm'
    | '/app/eventos'
    | '/app/financeiro'
    | '/app/juridico'
    | '/app/kanban'
    | '/app/logistica'
    | '/app/palestrantes'
    | '/app/prebalanco'
    | '/app/propostas'
    | '/app/vendas'
    | '/palestrante/$id'
    | '/app'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/catalogo'
    | '/orcamento'
    | '/portal'
    | '/app/admin'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/crm'
    | '/app/eventos'
    | '/app/financeiro'
    | '/app/juridico'
    | '/app/kanban'
    | '/app/logistica'
    | '/app/palestrantes'
    | '/app/prebalanco'
    | '/app/propostas'
    | '/app/vendas'
    | '/palestrante/$id'
    | '/app/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PortalRoute: typeof PortalRouteWithChildren
  PalestranteIdRoute: typeof PalestranteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/palestrante/$id': {
      id: '/palestrante/$id'
      path: '/palestrante/$id'
      fullPath: '/palestrante/$id'
      preLoaderRoute: typeof PalestranteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prebalanco': {
      id: '/app/prebalanco'
      path: '/prebalanco'
      fullPath: '/app/prebalanco'
      preLoaderRoute: typeof AppPrebalancoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/palestrantes': {
      id: '/app/palestrantes'
      path: '/palestrantes'
      fullPath: '/app/palestrantes'
      preLoaderRoute: typeof AppPalestrantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistica': {
      id: '/app/logistica'
      path: '/logistica'
      fullPath: '/app/logistica'
      preLoaderRoute: typeof AppLogisticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/juridico': {
      id: '/app/juridico'
      path: '/juridico'
      fullPath: '/app/juridico'
      preLoaderRoute: typeof AppJuridicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comissoes': {
      id: '/app/comissoes'
      path: '/comissoes'
      fullPath: '/app/comissoes'
      preLoaderRoute: typeof AppComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComissoesRoute: typeof AppComissoesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppEventosRoute: typeof AppEventosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppJuridicoRoute: typeof AppJuridicoRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppLogisticaRoute: typeof AppLogisticaRoute
  AppPalestrantesRoute: typeof AppPalestrantesRoute
  AppPrebalancoRoute: typeof AppPrebalancoRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClientesRoute: AppClientesRoute,
  AppComissoesRoute: AppComissoesRoute,
  AppCrmRoute: AppCrmRoute,
  AppEventosRoute: AppEventosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppJuridicoRoute: AppJuridicoRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppLogisticaRoute: AppLogisticaRoute,
  AppPalestrantesRoute: AppPalestrantesRoute,
  AppPrebalancoRoute: AppPrebalancoRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  OrcamentoRoute: OrcamentoRoute,
  PortalRoute: PortalRouteWithChildren,
  PalestranteIdRoute: PalestranteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
